-- MySQL Script generated by MySQL Workbench
-- Tue Jun  5 11:20:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema swt1821DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema swt1821DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `swt1821DB` ;
USE `swt1821DB` ;

-- -----------------------------------------------------
-- Table `swt1821DB`.`Vehikel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swt1821DB`.`Vehikel` (
  `Name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Name`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC))
ENGINE = InnoDB
MAX_ROWS = 4
MIN_ROWS = 4;

INSERT INTO `swt1821DB`.`Vehikel`(Name)  -- einfügen des Vehikels Fahrradfahren
VALUES ('bycicling');

INSERT INTO `swt1821DB`.`Vehikel`(Name)	 -- einfügen des Vehikels zu Fuß
VALUES ('walking');

INSERT INTO `swt1821DB`.`Vehikel`(Name)  -- einfügen des Vehikels ÖPNV
VALUES ('transit');

INSERT INTO `swt1821DB`.`Vehikel`(Name)  -- einfügen des Vehikels Auto
VALUES ('driving');


-- -----------------------------------------------------
-- Table `swt1821DB`.`Nutzer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swt1821DB`.`Nutzer` (
  `eMail` VARCHAR(40) NOT NULL,
  `passwort` VARCHAR(20) NOT NULL,
  `Vehikel_Name` VARCHAR(15) NOT NULL,
  `Standort` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`eMail`),
  UNIQUE INDEX `eMail_UNIQUE` (`eMail` ASC),
  INDEX `fk_Nutzer_Vehikel_idx` (`Vehikel_Name` ASC),
  CONSTRAINT `fk_Nutzer_Vehikel`
    FOREIGN KEY (`Vehikel_Name`)
    REFERENCES `swt1821DB`.`Vehikel` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swt1821DB`.`Atmosphaere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swt1821DB`.`Atmosphaere` (
  `atmosphere` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`atmosphere`),
  UNIQUE INDEX `atmosphere_UNIQUE` (`atmosphere` ASC))
ENGINE = InnoDB;

INSERT INTO `swt1821DB`.`Atmosphaere` (atmosphere)
VALUES ('gesellig');

INSERT INTO `swt1821DB`.`Atmosphaere` (atmosphere)
VALUES ('gruppenarbeit');

INSERT INTO `swt1821DB`.`Atmosphaere` (atmosphere)
VALUES ('einzelarbeit');


-- -----------------------------------------------------
-- Table `swt1821DB`.`Gruppe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swt1821DB`.`Gruppe` (
  `kuerzel` VARCHAR(4) NOT NULL,
  `gruppenname` VARCHAR(45) NULL,
  `Atmosphaere_atmosphere` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`kuerzel`),
  UNIQUE INDEX `kuerzel_UNIQUE` (`kuerzel` ASC),
  INDEX `fk_Gruppe_Atmosphaere1_idx` (`Atmosphaere_atmosphere` ASC),
  CONSTRAINT `fk_Gruppe_Atmosphaere1`
    FOREIGN KEY (`Atmosphaere_atmosphere`)
    REFERENCES `swt1821DB`.`Atmosphaere` (`atmosphere`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swt1821DB`.`ist_in`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swt1821DB`.`ist_in` (
  `Nutzer_eMail` VARCHAR(40) NOT NULL,
  `Gruppe_kuerzel` VARCHAR(4) NOT NULL,
  INDEX `fk_ist_in_Nutzer1_idx` (`Nutzer_eMail` ASC),
  INDEX `fk_ist_in_Gruppe1_idx` (`Gruppe_kuerzel` ASC),
  CONSTRAINT `fk_ist_in_Nutzer1`
    FOREIGN KEY (`Nutzer_eMail`)
    REFERENCES `swt1821DB`.`Nutzer` (`eMail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ist_in_Gruppe1`
    FOREIGN KEY (`Gruppe_kuerzel`)
    REFERENCES `swt1821DB`.`Gruppe` (`kuerzel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swt1821DB`.``swt1821DB`.`Standort``
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swt1821DB`.`Standort`` (
  `id`swt1821DB`.`Standort`` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `adresse_strasse` VARCHAR(45) NULL,
  `Atmosphaere_atmosphere` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id`swt1821DB`.`Standort``),
  INDEX `fk_`swt1821DB`.`Standort`_Atmosphaere1_idx` (`Atmosphaere_atmosphere` ASC),
  CONSTRAINT `fk_`swt1821DB`.`Standort`_Atmosphaere1`
    FOREIGN KEY (`Atmosphaere_atmosphere`)
    REFERENCES `swt1821DB`.`Atmosphaere` (`atmosphere`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('JAZ','Lindenstraße 3b','gesellig');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Eiscafe Milano','Kröpeliner Straße 26','gesellig');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Eiswerkstatt','Kröpeliner Straße 18','gesellig');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Eisscholle','Waldemarstraße 5','gesellig');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Zwanzig 12','Schnickmannstraße 14','gesellig');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Losteria','Steinstraße 9','gesellig');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('schusters Strandbar','Seepromenade 1','gesellig');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Alex','Neuer Markt 17-18','gesellig');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Vapiano','Neuer Markt 9-10','gesellig');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Peter Pane','Kröpeliner Straße 25','gesellig');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('LT-Club','Tiergartenallee 1-2','gesellig');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('ST-Club','Albert-Einstein-Straße 2','gesellig');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Bunker','Neptunallee 8','gesellig');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Allround Arena','Kolumbusring 61','gesellig');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Bacio Club','Am Strande 3','gesellig');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Besitos','Warnowufer','gesellig');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Da Capo','Seestraße 19','gesellig');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Greifclub','Schillingallee 41','gesellig');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Helgas Stadtpalast','Vögenteich 19','gesellig');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Mau-Club','Stadthafengebäude 603','gesellig');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Peter Weiß Haus','Doberaner Straße 21','gesellig');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Studentenclub','Richard Wagner Straße 31','gesellig');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Studentenkeller','Universitätsplatz 5','gesellig');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Theater des Friedens','Doberaner Straße 5','gesellig');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Zwischenbau','Erich-Schlesinger Straße 19a','gesellig');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Konrad-Zuse Haus','Albert-Einstein-Straße 22','gruppenarbeit');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('UB Rostock:Bibliothe Südstadt','Albert-Einstein-Straße 6','gruppenarbeit');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Stadtbibliothek','Kröpeliner Straße 82','gruppenarbeit');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Grünes Ungeheuer','Parkstraße 6','gruppenarbeit');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Ulmencampus','Ulmenstraße 69','gruppenarbeit');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Uni Hauptgebäude','Universitätsplatz 1','gruppenarbeit');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Philosophische Fakultät','August-Bebel-Straße 28','gruppenarbeit');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Agrawissenschaft','Justus-von-Liebig-Weg 6','gruppenarbeit');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Uni Medizin','Strempelstraße 14','gruppenarbeit');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Universitätsmedizin','Schillingstraße 35','gruppenarbeit');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Institut für Chemie','Albert-Einstein-Straße 3a','gruppenarbeit');

INSERT INTO `swt1821DB`.`Standort` (Bezeichnung,Anschrift,Atmosphaere_atmosphere)
VALUES ('Institut für Elektrotechnik','Albert-Einstein-Straße 2','gruppenarbeit');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
